// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/backtest.proto

package signalstackv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunBacktestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"` // correlation id (optional for now)
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`            // e.g. "AAPL"
	Timeframe     string                 `protobuf:"bytes,3,opt,name=timeframe,proto3" json:"timeframe,omitempty"`      // e.g. "1D"
	Start         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end,proto3" json:"end,omitempty"`
	StrategyId    string                 `protobuf:"bytes,6,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`                                                 // e.g. "SMA_CROSS"
	Params        map[string]string      `protobuf:"bytes,7,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // strategy-specific params
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunBacktestRequest) Reset() {
	*x = RunBacktestRequest{}
	mi := &file_proto_backtest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunBacktestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunBacktestRequest) ProtoMessage() {}

func (x *RunBacktestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backtest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunBacktestRequest.ProtoReflect.Descriptor instead.
func (*RunBacktestRequest) Descriptor() ([]byte, []int) {
	return file_proto_backtest_proto_rawDescGZIP(), []int{0}
}

func (x *RunBacktestRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunBacktestRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RunBacktestRequest) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *RunBacktestRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *RunBacktestRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *RunBacktestRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *RunBacktestRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type RunBacktestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	StrategyId    string                 `protobuf:"bytes,3,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Metrics       *BacktestMetrics       `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Trades        []*Trade               `protobuf:"bytes,5,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunBacktestResponse) Reset() {
	*x = RunBacktestResponse{}
	mi := &file_proto_backtest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunBacktestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunBacktestResponse) ProtoMessage() {}

func (x *RunBacktestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backtest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunBacktestResponse.ProtoReflect.Descriptor instead.
func (*RunBacktestResponse) Descriptor() ([]byte, []int) {
	return file_proto_backtest_proto_rawDescGZIP(), []int{1}
}

func (x *RunBacktestResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RunBacktestResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RunBacktestResponse) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *RunBacktestResponse) GetMetrics() *BacktestMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *RunBacktestResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

type BacktestMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cagr          float64                `protobuf:"fixed64,1,opt,name=cagr,proto3" json:"cagr,omitempty"`
	MaxDrawdown   float64                `protobuf:"fixed64,2,opt,name=max_drawdown,json=maxDrawdown,proto3" json:"max_drawdown,omitempty"` // fraction (0.2 = 20%)
	WinRate       float64                `protobuf:"fixed64,3,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`             // fraction
	ProfitFactor  float64                `protobuf:"fixed64,4,opt,name=profit_factor,json=profitFactor,proto3" json:"profit_factor,omitempty"`
	FinalEquity   float64                `protobuf:"fixed64,5,opt,name=final_equity,json=finalEquity,proto3" json:"final_equity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BacktestMetrics) Reset() {
	*x = BacktestMetrics{}
	mi := &file_proto_backtest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BacktestMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacktestMetrics) ProtoMessage() {}

func (x *BacktestMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backtest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktestMetrics.ProtoReflect.Descriptor instead.
func (*BacktestMetrics) Descriptor() ([]byte, []int) {
	return file_proto_backtest_proto_rawDescGZIP(), []int{2}
}

func (x *BacktestMetrics) GetCagr() float64 {
	if x != nil {
		return x.Cagr
	}
	return 0
}

func (x *BacktestMetrics) GetMaxDrawdown() float64 {
	if x != nil {
		return x.MaxDrawdown
	}
	return 0
}

func (x *BacktestMetrics) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

func (x *BacktestMetrics) GetProfitFactor() float64 {
	if x != nil {
		return x.ProfitFactor
	}
	return 0
}

func (x *BacktestMetrics) GetFinalEquity() float64 {
	if x != nil {
		return x.FinalEquity
	}
	return 0
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Side          string                 `protobuf:"bytes,1,opt,name=side,proto3" json:"side,omitempty"`         // "BUY"/"SELL" (closing order side)
	Position      string                 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"` // "LONG"/"SHORT"
	EntryTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=entry_time,json=entryTime,proto3" json:"entry_time,omitempty"`
	EntryPrice    float64                `protobuf:"fixed64,4,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	ExitTime      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=exit_time,json=exitTime,proto3" json:"exit_time,omitempty"`
	ExitPrice     float64                `protobuf:"fixed64,6,opt,name=exit_price,json=exitPrice,proto3" json:"exit_price,omitempty"`
	Size          float64                `protobuf:"fixed64,7,opt,name=size,proto3" json:"size,omitempty"`
	Pnl           float64                `protobuf:"fixed64,8,opt,name=pnl,proto3" json:"pnl,omitempty"`
	RMultiple     float64                `protobuf:"fixed64,9,opt,name=r_multiple,json=rMultiple,proto3" json:"r_multiple,omitempty"` // 0 if unset; you can make this optional later if you want
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_proto_backtest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_proto_backtest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_proto_backtest_proto_rawDescGZIP(), []int{3}
}

func (x *Trade) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Trade) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Trade) GetEntryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EntryTime
	}
	return nil
}

func (x *Trade) GetEntryPrice() float64 {
	if x != nil {
		return x.EntryPrice
	}
	return 0
}

func (x *Trade) GetExitTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExitTime
	}
	return nil
}

func (x *Trade) GetExitPrice() float64 {
	if x != nil {
		return x.ExitPrice
	}
	return 0
}

func (x *Trade) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Trade) GetPnl() float64 {
	if x != nil {
		return x.Pnl
	}
	return 0
}

func (x *Trade) GetRMultiple() float64 {
	if x != nil {
		return x.RMultiple
	}
	return 0
}

var File_proto_backtest_proto protoreflect.FileDescriptor

const file_proto_backtest_proto_rawDesc = "" +
	"\n" +
	"\x14proto/backtest.proto\x12\x0esignalstack.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x02\n" +
	"\x12RunBacktestRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1c\n" +
	"\ttimeframe\x18\x03 \x01(\tR\ttimeframe\x120\n" +
	"\x05start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12\x1f\n" +
	"\vstrategy_id\x18\x06 \x01(\tR\n" +
	"strategyId\x12F\n" +
	"\x06params\x18\a \x03(\v2..signalstack.v1.RunBacktestRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcf\x01\n" +
	"\x13RunBacktestResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1f\n" +
	"\vstrategy_id\x18\x03 \x01(\tR\n" +
	"strategyId\x129\n" +
	"\ametrics\x18\x04 \x01(\v2\x1f.signalstack.v1.BacktestMetricsR\ametrics\x12-\n" +
	"\x06trades\x18\x05 \x03(\v2\x15.signalstack.v1.TradeR\x06trades\"\xab\x01\n" +
	"\x0fBacktestMetrics\x12\x12\n" +
	"\x04cagr\x18\x01 \x01(\x01R\x04cagr\x12!\n" +
	"\fmax_drawdown\x18\x02 \x01(\x01R\vmaxDrawdown\x12\x19\n" +
	"\bwin_rate\x18\x03 \x01(\x01R\awinRate\x12#\n" +
	"\rprofit_factor\x18\x04 \x01(\x01R\fprofitFactor\x12!\n" +
	"\ffinal_equity\x18\x05 \x01(\x01R\vfinalEquity\"\xb0\x02\n" +
	"\x05Trade\x12\x12\n" +
	"\x04side\x18\x01 \x01(\tR\x04side\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\tR\bposition\x129\n" +
	"\n" +
	"entry_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tentryTime\x12\x1f\n" +
	"\ventry_price\x18\x04 \x01(\x01R\n" +
	"entryPrice\x127\n" +
	"\texit_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bexitTime\x12\x1d\n" +
	"\n" +
	"exit_price\x18\x06 \x01(\x01R\texitPrice\x12\x12\n" +
	"\x04size\x18\a \x01(\x01R\x04size\x12\x10\n" +
	"\x03pnl\x18\b \x01(\x01R\x03pnl\x12\x1d\n" +
	"\n" +
	"r_multiple\x18\t \x01(\x01R\trMultiple2k\n" +
	"\x0fBacktestService\x12X\n" +
	"\vRunBacktest\x12\".signalstack.v1.RunBacktestRequest\x1a#.signalstack.v1.RunBacktestResponse\"\x00B4Z2signalstack/gen/proto/signalstack/v1;signalstackv1b\x06proto3"

var (
	file_proto_backtest_proto_rawDescOnce sync.Once
	file_proto_backtest_proto_rawDescData []byte
)

func file_proto_backtest_proto_rawDescGZIP() []byte {
	file_proto_backtest_proto_rawDescOnce.Do(func() {
		file_proto_backtest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_backtest_proto_rawDesc), len(file_proto_backtest_proto_rawDesc)))
	})
	return file_proto_backtest_proto_rawDescData
}

var file_proto_backtest_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_backtest_proto_goTypes = []any{
	(*RunBacktestRequest)(nil),    // 0: signalstack.v1.RunBacktestRequest
	(*RunBacktestResponse)(nil),   // 1: signalstack.v1.RunBacktestResponse
	(*BacktestMetrics)(nil),       // 2: signalstack.v1.BacktestMetrics
	(*Trade)(nil),                 // 3: signalstack.v1.Trade
	nil,                           // 4: signalstack.v1.RunBacktestRequest.ParamsEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_backtest_proto_depIdxs = []int32{
	5, // 0: signalstack.v1.RunBacktestRequest.start:type_name -> google.protobuf.Timestamp
	5, // 1: signalstack.v1.RunBacktestRequest.end:type_name -> google.protobuf.Timestamp
	4, // 2: signalstack.v1.RunBacktestRequest.params:type_name -> signalstack.v1.RunBacktestRequest.ParamsEntry
	2, // 3: signalstack.v1.RunBacktestResponse.metrics:type_name -> signalstack.v1.BacktestMetrics
	3, // 4: signalstack.v1.RunBacktestResponse.trades:type_name -> signalstack.v1.Trade
	5, // 5: signalstack.v1.Trade.entry_time:type_name -> google.protobuf.Timestamp
	5, // 6: signalstack.v1.Trade.exit_time:type_name -> google.protobuf.Timestamp
	0, // 7: signalstack.v1.BacktestService.RunBacktest:input_type -> signalstack.v1.RunBacktestRequest
	1, // 8: signalstack.v1.BacktestService.RunBacktest:output_type -> signalstack.v1.RunBacktestResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_backtest_proto_init() }
func file_proto_backtest_proto_init() {
	if File_proto_backtest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_backtest_proto_rawDesc), len(file_proto_backtest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_backtest_proto_goTypes,
		DependencyIndexes: file_proto_backtest_proto_depIdxs,
		MessageInfos:      file_proto_backtest_proto_msgTypes,
	}.Build()
	File_proto_backtest_proto = out.File
	file_proto_backtest_proto_goTypes = nil
	file_proto_backtest_proto_depIdxs = nil
}
