// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/backtest.proto

package signalstackv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BacktestService_RunBacktest_FullMethodName = "/signalstack.v1.BacktestService/RunBacktest"
)

// BacktestServiceClient is the client API for BacktestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BacktestServiceClient interface {
	RunBacktest(ctx context.Context, in *RunBacktestRequest, opts ...grpc.CallOption) (*RunBacktestResponse, error)
}

type backtestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBacktestServiceClient(cc grpc.ClientConnInterface) BacktestServiceClient {
	return &backtestServiceClient{cc}
}

func (c *backtestServiceClient) RunBacktest(ctx context.Context, in *RunBacktestRequest, opts ...grpc.CallOption) (*RunBacktestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunBacktestResponse)
	err := c.cc.Invoke(ctx, BacktestService_RunBacktest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BacktestServiceServer is the server API for BacktestService service.
// All implementations must embed UnimplementedBacktestServiceServer
// for forward compatibility.
type BacktestServiceServer interface {
	RunBacktest(context.Context, *RunBacktestRequest) (*RunBacktestResponse, error)
	mustEmbedUnimplementedBacktestServiceServer()
}

// UnimplementedBacktestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBacktestServiceServer struct{}

func (UnimplementedBacktestServiceServer) RunBacktest(context.Context, *RunBacktestRequest) (*RunBacktestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunBacktest not implemented")
}
func (UnimplementedBacktestServiceServer) mustEmbedUnimplementedBacktestServiceServer() {}
func (UnimplementedBacktestServiceServer) testEmbeddedByValue()                         {}

// UnsafeBacktestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BacktestServiceServer will
// result in compilation errors.
type UnsafeBacktestServiceServer interface {
	mustEmbedUnimplementedBacktestServiceServer()
}

func RegisterBacktestServiceServer(s grpc.ServiceRegistrar, srv BacktestServiceServer) {
	// If the following call panics, it indicates UnimplementedBacktestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BacktestService_ServiceDesc, srv)
}

func _BacktestService_RunBacktest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunBacktestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BacktestServiceServer).RunBacktest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BacktestService_RunBacktest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BacktestServiceServer).RunBacktest(ctx, req.(*RunBacktestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BacktestService_ServiceDesc is the grpc.ServiceDesc for BacktestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BacktestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "signalstack.v1.BacktestService",
	HandlerType: (*BacktestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunBacktest",
			Handler:    _BacktestService_RunBacktest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/backtest.proto",
}
